# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.cache/wt [current_project]
set_property parent.project_path E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/program/cpu/SCCPU_FPGA/SCCPU_SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/program/cpu/dino.coe
read_verilog -library xil_defaultlib {
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/ctrl_encode_def.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/EXT.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/MIO_BUS.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/Multi_CH32.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/NPC.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/PC.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/RF.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/SCCPU.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/alu.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/clk_div.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/ctrl.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/dm.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/seg7x16.v
  E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/imports/codtest/RVSCCPU_Top.v
}
read_ip -quiet E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all e:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/constrs_1/imports/constraints/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files E:/program/cpu/SCCPU_FPGA/SCCPU_SOC.srcs/constrs_1/imports/constraints/Nexys4DDR_CPU.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RVSCCPUSOC_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RVSCCPUSOC_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RVSCCPUSOC_Top_utilization_synth.rpt -pb RVSCCPUSOC_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
